version: '3.8'

services:

  app:
    build: .
    ports:
      - 3005:3005
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mongo:6.0.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
